spring:
  application:
    name: Customers
    
server:
  port: 8081
  
composition:
  messagebroker:
    type: rabbitmq
    host: 172.23.180.72
    port: 5672
    user: microservice
    password: microservice
    exchange: composition
  fragmentmanager:
    url: http://localhost:8083
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka